AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'Gemfile.lock'

Metrics/MethodLength:
  Max: 25
Metrics/LineLength:
  Max: 120
Bundler/OrderedGems:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
